### ISSUE TITLE
Dependency tree error

### ISSUE THREAD

**Issue by lewisdonovan** [fabioberger/love_chain_project#5]
I get a dependency conflict error when running `npm install`:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: CryptoValentine@0.1.0
npm ERR! Found: react@15.4.2
npm ERR! node_modules/react
npm ERR!   react@"15.4.x" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@">=^16.0.0" from react-tooltip@3.11.6
npm ERR! node_modules/react-tooltip
npm ERR!   react-tooltip@"^3.2.6" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/user/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2021-01-28T13_55_33_178Z-debug.log
```

Here's the npm error resolution report:
```
# npm resolution error report

2021-01-28T13:56:18.566Z

While resolving: CryptoValentine@0.1.0
Found: react@15.4.2
node_modules/react
  react@"15.4.x" from the root project

Could not resolve dependency:
peer react@">=^16.0.0" from react-tooltip@3.11.6
node_modules/react-tooltip
  react-tooltip@"^3.2.6" from the root project

Fix the upstream dependency conflict, or retry
this command with --force, or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.

Raw JSON explanation object:

{
  "code": "ERESOLVE",
  "current": {
    "name": "react",
    "version": "15.4.2",
    "whileInstalling": {
      "name": "CryptoValentine",
      "version": "0.1.0",
      "path": "/Users/user/Documents/web-projects/love_chain_project"
    },
    "location": "node_modules/react",
    "dependents": [
      {
        "type": "prod",
        "name": "react",
        "spec": "15.4.x",
        "from": {
          "location": "/Users/user/Documents/web-projects/love_chain_project"
        }
      }
    ]
  },
  "edge": {
    "type": "peer",
    "name": "react",
    "spec": ">=^16.0.0",
    "error": "INVALID",
    "from": {
      "name": "react-tooltip",
      "version": "3.11.6",
      "errors": [
        {
          "code": "EINVALIDTAGNAME",
          "dependency": "react",
          "requested": ">=^16.0.0"
        }
      ],
      "package": {
        "name": "react-tooltip",
        "version": "3.11.6",
        "dependencies": {
          "prop-types": "^15.6.0"
        },
        "devDependencies": {
          "@babel/cli": "^7.7.4",
          "@babel/core": "^7.7.4",
          "@babel/plugin-proposal-class-properties": "^7.7.4",
          "@babel/plugin-proposal-decorators": "^7.7.4",
          "@babel/preset-env": "^7.7.4",
          "@babel/preset-react": "^7.7.4",
          "@svgr/rollup": "^4.3.3",
          "babel-eslint": "^4.1.1",
          "babel-plugin-syntax-decorators": "^6.13.0",
          "babelify": "^7.2.0",
          "browserify": "^13.0.0",
          "browserify-shim": "^3.8.12",
          "chai": "^3.5.0",
          "chai-enzyme": "^0.5.0",
          "commitizen": "2.9.6",
          "concurrently": "^2.1.0",
          "cz-conventional-changelog": "2.1.0",
          "enzyme": "^2.3.0",
          "enzyme-adapter-react-16": "^1.0.1",
          "eslint": "^6.7.1",
          "eslint-config-prettier": "^6.7.0",
          "eslint-config-standard": "^14.1.0",
          "eslint-config-standard-react": "^9.2.0",
          "eslint-plugin-import": "^2.18.2",
          "eslint-plugin-node": "^10.0.0",
          "eslint-plugin-prettier": "^3.1.1",
          "eslint-plugin-promise": "^4.2.1",
          "eslint-plugin-react": "^7.16.0",
          "eslint-plugin-standard": "^4.0.1",
          "gh-pages": "1.1.0",
          "github-changes": "^1.1.2",
          "http-server": "^0.11.1",
          "jsdom": "^9.2.1",
          "mocha": "^5.2.0",
          "node-sass": "^4.13.0",
          "npm-run-all": "^4.1.5",
          "postcss-nested": "^4.2.1",
          "postcss-simple-vars": "^5.0.2",
          "prettier": "^1.19.1",
          "react": "^16.4.1",
          "react-addons-test-utils": "^15.1.0",
          "react-dom": "^16.4.1",
          "rimraf": "^3.0.0",
          "rollup": "^1.27.5",
          "rollup-plugin-babel": "^4.3.3",
          "rollup-plugin-commonjs": "^10.1.0",
          "rollup-plugin-node-resolve": "^5.2.0",
          "rollup-plugin-peer-deps-external": "^2.2.0",
          "rollup-plugin-postcss": "^2.0.3",
          "rollup-plugin-sass": "^1.2.2",
          "rollup-plugin-url": "^3.0.1",
          "semantic-release": "15.1.5",
          "sinon": "^1.17.4",
          "snazzy": "^2.0.1",
          "standard": "^5.2.2",
          "uglifyjs": "^2.4.10",
          "watchify": "^3.11.0"
        },
        "peerDependencies": {
          "react": ">=^16.0.0",
          "react-dom": ">=^16.0.0"
        },
        "dist": {
          "integrity": "sha512-nTc1yHHaPCHHURvMpf/VNF17pIZiU4zwUGFJBUVr1fZkezFC7E0VPMMVrCfDjt+IpwTHICyzlyx+1FiQ7lw5LQ==",
          "shasum": "4f9735a2a4aa50580af351ce23e74a56f41afc0c",
          "tarball": "https://registry.npmjs.org/react-tooltip/-/react-tooltip-3.11.6.tgz",
          "fileCount": 8,
          "unpackedSize": 492596,
          "npm-signature": "-----BEGIN PGP SIGNATURE-----\r\nVersion: OpenPGP.js v3.0.4\r\nComment: https://openpgpjs.org\r\n\r\nwsFcBAEBCAAQBQJeO2sjCRA9TVsSAnZWagAAwvIP/RzxdDHpkt3lEOJYX7B1\nOpAu4dEqxN3mCXuVvWFUNYhgFBYNr6F8Ixq3vf9bYsFQuJOwPAFhZB1AL6CH\nxiHmf5I0TY41G0Gd6Of+xFxwb9wfSmOKxb/8rbEl3R2x0Oi3rP53jYarnM6k\nG9G6nKQN7DAN2Qq31x1u9V91A/WiWO3AhYdBmZirr8uHbS5jEGIVZOyCF6l8\nln95iWmxtQSOawBzvXvcF3A5YHCOC9UpL86nV6YoEZK/l4i5JXuiaV28IKhh\nuhouMyFPWpsqqTgYtUiUyb4XnOkThCd0qb+SU9pt8x8Jh5jaPZmX0DnlaIH3\ndF+TZRbop/FEyUs3PY6RRf84rmQ9biUk+HspdHM2UT+qg7X40ai550OHdHEU\nTAvTcZReXTNhqvUisymbmGRFCLLUC2XleAa2KIbSBNeWt+bpnP08Vhr4uSwd\nkKodFjR4gKkrFC0OsimGlTEN9aIlnN4ZdxU80NsEeAw1qRBtF67tQ0B/UHfq\no+Hz3t9YHR+QG8O+3U5Xpe0013I1TTpK/pD4cLTe25EWN/64S59zjPfvHWBV\nVtqN4CdFl6yIriTLEtwrKtWeD1/0Dided8FzTa4zhCcmEl/A/2JwmaVQFGLA\ncnexPbiFyCTeJU3BVR0clJ+siQ2Vjsbo5LLCWZSB3j0ufrh+C8pxipnE9P01\nTEer\r\n=eqnh\r\n-----END PGP SIGNATURE-----\r\n"
        },
        "engines": {
          "node": ">=8",
          "npm": ">=5"
        },
        "_resolved": "https://registry.npmjs.org/react-tooltip/-/react-tooltip-3.11.6.tgz",
        "_from": "react-tooltip@^3.2.6",
        "_integrity": "sha512-nTc1yHHaPCHHURvMpf/VNF17pIZiU4zwUGFJBUVr1fZkezFC7E0VPMMVrCfDjt+IpwTHICyzlyx+1FiQ7lw5LQ==",
        "_id": "react-tooltip@3.11.6"
      },
      "whileInstalling": {
        "name": "CryptoValentine",
        "version": "0.1.0",
        "path": "/Users/user/Documents/web-projects/love_chain_project"
      },
      "location": "node_modules/react-tooltip",
      "dependents": [
        {
          "type": "prod",
          "name": "react-tooltip",
          "spec": "^3.2.6",
          "from": {
            "location": "/Users/user/Documents/web-projects/love_chain_project"
          }
        }
      ]
    }
  },
  "peerConflict": null,
  "strictPeerDeps": false,
  "force": false
}
```

And here's the debug log:
```
0 verbose cli [ '/usr/local/Cellar/node/15.3.0/bin/node', '/usr/local/bin/npm', 'i' ]
1 info using npm@7.0.14
2 info using node@v15.3.0
3 timing config:load:defaults Completed in 1ms
4 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 1ms
5 timing config:load:builtin Completed in 1ms
6 timing config:load:cli Completed in 1ms
7 timing config:load:env Completed in 1ms
8 timing config:load:file:/Users/user/Documents/web-projects/love_chain_project/.npmrc Completed in 0ms
9 timing config:load:project Completed in 0ms
10 timing config:load:file:/Users/user/.npmrc Completed in 1ms
11 timing config:load:user Completed in 1ms
12 timing config:load:file:/usr/local/etc/npmrc Completed in 1ms
13 timing config:load:global Completed in 1ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 7ms
19 verbose npm-session 8f89aefa422ee9ff
20 timing npm:load Completed in 14ms
21 http fetch GET 200 https://registry.npmjs.org/npm 670ms
22 timing arborist:ctor Completed in 1ms
23 timing arborist:ctor Completed in 0ms
24 timing idealTree:init Completed in 9ms
25 timing idealTree:userRequests Completed in 0ms
26 silly idealTree buildDeps
27 silly fetch manifest Faker@^0.7.2
28 http fetch GET 200 https://registry.npmjs.org/Faker 746ms
29 silly fetch manifest basscss@^8.0.2
30 http fetch GET 200 https://registry.npmjs.org/basscss 1064ms
31 silly fetch manifest classnames@^2.2.5
32 http fetch GET 200 https://registry.npmjs.org/classnames 130ms
33 silly fetch manifest cookies-js@^1.2.3
34 http fetch GET 200 https://registry.npmjs.org/cookies-js 60ms
35 silly fetch manifest deep-equal@^1.0.1
36 http fetch GET 304 https://registry.npmjs.org/deep-equal 47ms (from cache)
37 silly fetch manifest eventemitter2@^3.0.0
38 http fetch GET 200 https://registry.npmjs.org/eventemitter2 39ms
39 silly fetch manifest joi-browser@^10.0.6
40 http fetch GET 200 https://registry.npmjs.org/joi-browser 46ms
41 silly fetch manifest json-loader@^0.5.4
42 http fetch GET 200 https://registry.npmjs.org/json-loader 69ms
43 silly fetch manifest less@2.6.x
44 http fetch GET 200 https://registry.npmjs.org/less 86ms
45 silly fetch manifest lodash@^4.17.2
46 http fetch GET 200 https://registry.npmjs.org/lodash 283ms
47 silly fetch manifest material-ui@^0.16.7
48 http fetch GET 200 https://registry.npmjs.org/material-ui 77ms
49 silly fetch manifest react@15.4.x
50 http fetch GET 200 https://registry.npmjs.org/react 89ms
51 silly fetch manifest react-dom@15.4.x
52 http fetch GET 200 https://registry.npmjs.org/react-dom 75ms
53 silly fetch manifest react-tap-event-plugin@^2.0.1
54 http fetch GET 200 https://registry.npmjs.org/react-tap-event-plugin 773ms
55 silly fetch manifest react-addons-css-transition-group@^15.4.2
56 http fetch GET 200 https://registry.npmjs.org/react-addons-css-transition-group 48ms
57 silly fetch manifest react-copy-to-clipboard@^4.2.3
58 http fetch GET 200 https://registry.npmjs.org/react-copy-to-clipboard 65ms
59 silly fetch manifest react-github-fork-ribbon@0.4.4
60 http fetch GET 200 https://registry.npmjs.org/react-github-fork-ribbon 1049ms
61 silly fetch manifest react-inlinesvg@^0.5.5
62 http fetch GET 200 https://registry.npmjs.org/react-inlinesvg 1082ms
63 silly fetch manifest react-tooltip@^3.2.6
64 http fetch GET 200 https://registry.npmjs.org/react-tooltip 77ms
65 timing idealTree Completed in 6038ms
66 timing command:install Completed in 6042ms
67 verbose stack Error: unable to resolve dependency tree
67 verbose stack     at Arborist.[failPeerConflict] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1045:25)
67 verbose stack     at Arborist.[loadPeerSet] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1025:36)
67 verbose stack     at async Arborist.[buildDepStep] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:781:11)
67 verbose stack     at async Arborist.buildIdealTree (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:209:7)
67 verbose stack     at async Promise.all (index 1)
67 verbose stack     at async Arborist.reify (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:122:5)
67 verbose stack     at async install (/usr/local/lib/node_modules/npm/lib/install.js:39:3)
68 verbose cwd /Users/user/Documents/web-projects/love_chain_project
69 verbose Darwin 19.6.0
70 verbose argv "/usr/local/Cellar/node/15.3.0/bin/node" "/usr/local/bin/npm" "i"
71 verbose node v15.3.0
72 verbose npm  v7.0.14
73 error code ERESOLVE
74 error ERESOLVE unable to resolve dependency tree
75 error
76 error While resolving: [1mCryptoValentine[22m@[1m0.1.0[22m
76 error Found: [1mreact[22m@[1m15.4.2[22m[2m[22m
76 error [2mnode_modules/react[22m
76 error   [1mreact[22m@"[1m15.4.x[22m" from the root project
76 error
76 error Could not resolve dependency:
76 error [35mpeer[39m [1mreact[22m@"[1m>=^16.0.0[22m" from [1mreact-tooltip[22m@[1m3.11.6[22m[2m[22m
76 error [2mnode_modules/react-tooltip[22m
76 error   [1mreact-tooltip[22m@"[1m^3.2.6[22m" from the root project
76 error
76 error Fix the upstream dependency conflict, or retry
76 error this command with --force, or --legacy-peer-deps
76 error to accept an incorrect (and potentially broken) dependency resolution.
76 error
76 error See /Users/user/.npm/eresolve-report.txt for a full report.
77 verbose exit 1

```

**Comment by LogvinovLeon** [comment]
How on earth did you find this project? XD It hasn't been active since 2017?

**Comment by lewisdonovan** [comment]
Haha I was sent it by a colleague, we're looking to do maybe use it for a project.
